# Site settings
title: Lorelai Sonja
#logo:/
description: Your website description goes here
theme: jekyll-theme-cayman # Replace with the Jekyll theme you want to use

show_downloads: true 

#### Technical Skills: Python, MATLAB, R

## Education
- Post Graduate Certification, Data Science & Business Analytics | The University of Texas Austin (_May 2023_)								       		
- B.S., Psychology | St. Edward's University (_May 2023_)
- A.A.S., Business Technologies | Lake Washington Technical Institute (_May 2014_)

## Work Experience
**Data Analyst @ Luisa Mauro Real Estate (_July 2023 - Present_)**
- example of how I used data to increase revenue

**Data Analytics Translator & Consultant @ Integrated Insights, LLC (_May 2021 - Present_)**
- examples

## Projects
### Project Name


summary of project



## Talks & Lectures
- SWPA Conference
- Honors Thesis

## Publications
1. Honors Thesis

- Start Blog
